# Grid Search CV

In [1]:
import numpy as np
np.random.seed(14)

np.random.randint(low=0, high=10, size=10)

array([8, 6, 7, 9, 6, 0, 8, 9, 7, 6])

In [2]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV

In [3]:
X, y  = datasets.load_digits(return_X_y=True)

In [4]:
range(-10,10)

range(-10, 10)

Yo siempre quiero construir un diccionario que tenga los hiperparametros que quiero buscar

In [9]:
parameters = {'C': [2**i for i in range(-2,2)], 'gamma': [2**i for i in range(-2,2)]}

Construir un modelo base

In [10]:
svc = svm.SVC(kernel='rbf')

In [11]:
gs_clf = GridSearchCV(svc, parameters)

In [12]:
gs_clf.fit(X, y)

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.25, 0.5, 1, 2], 'gamma': [0.25, 0.5, 1, 2]})

In [13]:
print(type(gs_clf.best_estimator_))
gs_clf.best_estimator_

<class 'sklearn.svm._classes.SVC'>


SVC(C=0.25, gamma=0.5)

In [20]:
import pandas as pd
pd.DataFrame(gs_clf.cv_results_).sort_values("mean_test_score", ascending=False)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
1        0.271726      0.006894         0.062854        0.000571    0.25   
5        0.666467      0.273955         0.114648        0.015417     0.5   
2        0.241320      0.008408         0.055611        0.001125    0.25   
6        0.246827      0.011300         0.055793        0.001625     0.5   
10       0.245218      0.009036         0.055485        0.001301       1   
14       0.264916      0.006934         0.056102        0.001483       2   
3        0.211084      0.005048         0.054342        0.000756    0.25   
7        0.221658      0.007163         0.054443        0.001547     0.5   
11       0.221366      0.005207         0.055428        0.001347       1   
15       0.233577      0.007995         0.054152        0.000847       2   
0        0.645113      0.291430         0.158034        0.076821    0.25   
12       0.415907      0.071876         0.118170        0.021049       2   
13       0.342967      0.084526         0.071083        0.013526       2   
4        0.324907      0.064866         0.136749        0.069083     0.5   
8        0.283195      0.008984         0.079094        0.000603       1   
9        0.284795      0.008562         0.067825        0.006675       1   

   param_gamma                      params  split0_test_score  \
1          0.5   {'C': 0.25, 'gamma': 0.5}                0.1   
5          0.5    {'C': 0.5, 'gamma': 0.5}                0.1   
2            1     {'C': 0.25, 'gamma': 1}                0.1   
6            1      {'C': 0.5, 'gamma': 1}                0.1   
10           1        {'C': 1, 'gamma': 1}                0.1   
14           1        {'C': 2, 'gamma': 1}                0.1   
3            2     {'C': 0.25, 'gamma': 2}                0.1   
7            2      {'C': 0.5, 'gamma': 2}                0.1   
11           2        {'C': 1, 'gamma': 2}                0.1   
15           2        {'C': 2, 'gamma': 2}                0.1   
0         0.25  {'C': 0.25, 'gamma': 0.25}                0.1   
12        0.25     {'C': 2, 'gamma': 0.25}                0.1   
13         0.5      {'C': 2, 'gamma': 0.5}                0.1   
4         0.25   {'C': 0.5, 'gamma': 0.25}                0.1   
8         0.25     {'C': 1, 'gamma': 0.25}                0.1   
9          0.5      {'C': 1, 'gamma': 0.5}                0.1   

    split1_test_score  split2_test_score  split3_test_score  \
1                 0.1           0.103064           0.203343   
5                 0.1           0.103064           0.203343   
2                 0.1           0.103064           0.203343   
6                 0.1           0.103064           0.203343   
10                0.1           0.103064           0.203343   
14                0.1           0.103064           0.203343   
3                 0.1           0.178273           0.155989   
7                 0.1           0.178273           0.155989   
11                0.1           0.103064           0.155989   
15                0.1           0.103064           0.155989   
0                 0.1           0.103064           0.203343   
12                0.1           0.103064           0.103064   
13                0.1           0.103064           0.103064   
4                 0.1           0.103064           0.100279   
8                 0.1           0.103064           0.100279   
9                 0.1           0.103064           0.100279   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
1            0.197772         0.140836        0.048807                1  
5            0.197772         0.140836        0.048807                1  
2            0.189415         0.139164        0.046936                3  
6            0.189415         0.139164        0.046936                3  
10           0.189415         0.139164        0.046936                3  
14           0.189415         0.139164        0.046936                3  
3            0.

# Randomized Search CV

In [21]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform

In [22]:
iris = load_iris()

In [23]:
logistic = LogisticRegression(solver='saga', tol=1e-2, max_iter=200,
                              random_state=0)

In [25]:
distributions = dict(C=uniform(loc=0, scale=1000000),
                     penalty=['l2', 'l1'])

In [ ]:
RandomizedSearchCV(n_iter=50)

In [27]:
clf = RandomizedSearchCV(logistic, distributions, random_state=0)

In [28]:
search = clf.fit(iris.data, iris.target)
search.best_params_

{'C': 548813.5039273248, 'penalty': 'l1'}

In [30]:
import pandas as pd
pd.DataFrame(search.cv_results_).sort_values("mean_test_score", ascending=False)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.004005      0.001216         0.002096        0.002834   
1       0.002830      0.000095         0.000644        0.000132   
2       0.003119      0.000300         0.000595        0.000016   
3       0.002552      0.000135         0.000614        0.000076   
4       0.002479      0.000054         0.000544        0.000014   
5       0.002596      0.000280         0.000553        0.000022   
6       0.002455      0.000055         0.000562        0.000021   
7       0.002507      0.000080         0.000551        0.000008   
8       0.002739      0.000052         0.000545        0.000014   
9       0.002460      0.000054         0.000543        0.000031   

         param_C param_penalty                                     params  \
0  548813.503927            l1  {'C': 548813.5039273248, 'penalty': 'l1'}   
1  844265.748581            l1  {'C': 844265.7485810174, 'penalty': 'l1'}   
2  544883.182997            l1  {'C': 544883.1829968969, 'penalty': 'l1'}   
3  623563.696786            l2  {'C': 623563.6967859723, 'penalty': 'l2'}   
4  437587.211263            l2  {'C': 437587.2112626925, 'penalty': 'l2'}   
5   56712.977317            l2  {'C': 56712.97731744318, 'penalty': 'l2'}   
6  383441.518826            l2  {'C': 383441.5188257777, 'penalty': 'l2'}   
7  812168.728775            l2  {'C': 812168.7287754932, 'penalty': 'l2'}   
8  568044.561094            l1  {'C': 568044.5610939324, 'penalty': 'l1'}   
9  836078.763537            l2  {'C': 836078.7635373776, 'penalty': 'l2'}   

   split0_test_score  split1_test_score  split2_test_score  split3_test_score  \
0                1.0                1.0           0.966667           0.933333   
1                1.0                1.0           0.966667           0.933333   
2                1.0                1.0           0.966667           0.933333   
3                1.0                1.0           0.966667           0.933333   
4                1.0                1.0           0.966667           0.933333   
5                1.0                1.0           0.966667           0.933333   
6                1.0                1.0           0.966667           0.933333   
7                1.0                1.0           0.966667           0.933333   
8                1.0                1.0           0.966667           0.933333   
9                1.0                1.0           0.966667           0.933333   

   split4_test_score  mean_test_score  std_test_score  rank_test_score  
0                1.0             0.98        0.026667                1  
1                1.0             0.98        0.026667                1  
2                1.0             0.98        0.026667                1  
3                1.0             0.98        0.026667                1  
4                1.0             0.98        0.026667                1  
5                1.0             0.98        0.026667                1  
6                1.0             0.98        0.026667                1  
7                1.0             0.98        0.026667                1  
8                1.0             0.98        0.026667                1  
9                1.0             0.98        0.026667                1

In [31]:
from sklearn import tree

In [32]:
parameters = {'max_depth' : [1,10,100,1000,10000], 'max_features': [0.1,0.5,1.]}

In [33]:
from sklearn.metrics import cohen_kappa_score, make_scorer

In [34]:
model = tree.DecisionTreeClassifier()

In [35]:
from sklearn import ensemble
model = ensemble.RandomForestClassifier()

In [37]:
gs_clf = GridSearchCV(model, parameters, scoring='balanced_accuracy')

In [38]:
gs_clf.fit(X, y)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'max_depth': [1, 10, 100, 1000, 10000],
                         'max_features': [0.1, 0.5, 1.0]},
             scoring='balanced_accuracy')

In [53]:
feature_importances = gs_clf.best_estimator_.feature_importances_
print(feature_importances)
df = pd.DataFrame(feature_importances)
df.reset_index()
df.sort_values(0, ascending=False)

[0.00000000e+00 2.21954945e-03 2.08722283e-02 1.20846261e-02
 1.18111583e-02 2.08577495e-02 9.26258163e-03 5.52512241e-04
 7.25316643e-05 1.03033155e-02 2.80997712e-02 8.25907720e-03
 1.64126560e-02 2.80567312e-02 6.63951353e-03 4.97891096e-04
 7.80628536e-05 8.81432618e-03 2.08577666e-02 2.53877582e-02
 3.05049375e-02 4.88617978e-02 1.03165807e-02 2.19245510e-04
 6.25659537e-05 1.48912151e-02 3.79196532e-02 2.69326552e-02
 2.59966185e-02 2.55982114e-02 3.16171763e-02 6.08321536e-05
 0.00000000e+00 2.77417193e-02 2.84911185e-02 1.90441388e-02
 3.92158643e-02 2.01698324e-02 2.37434171e-02 0.00000000e+00
 2.06209853e-05 1.30034495e-02 3.40470123e-02 3.96037173e-02
 2.17856361e-02 1.80325057e-02 1.98433221e-02 8.89606873e-05
 7.06629370e-05 2.73650632e-03 1.83923071e-02 2.24669877e-02
 1.37430771e-02 2.26868303e-02 2.80751918e-02 1.61557580e-03
 5.66408401e-05 2.84547306e-03 2.23336068e-02 1.05624909e-02
 2.17093850e-02 2.56277987e-02 1.43526473e-02 3.77220735e-03]


0
21  0.048862
43  0.039604
36  0.039216
26  0.037920
42  0.034047
..       ...
56  0.000057
40  0.000021
0   0.000000
39  0.000000
32  0.000000

[64 rows x 1 columns]

en el punto 1.2 -> construir un arbol de decisión y fijar el random_State

construir un gridsearchcv, árbol, cv, los parametros

gridsearchcv entrenar con X_train, y y-train

In [ ]:
GridSearchCV(tree.DecisionTreeClassifier(), {'max_depth' : [1,10,100,1000,10000], 'max_features': [0.1,0.5,1.]}, scoring='balanced_accuracy').fit(X, y).best_estimator_.feature_importances_

In [ ]:
prueba = np.ones([50])

In [ ]:
valores = np.random.randint(low=0, high=10, size=10)
valores

In [ ]:
y = valores[3:]
y

In [ ]:
arreglo = []
for i in range(0, valores.shape[0]-2):
  arreglo.append(valores[i:i+3])
arreglo = np.array(arreglo)
arreglo

In [ ]:
arreglo[:-1]

In [ ]:
valores[3:]

In [ ]:
model = tree.DecisionTreeClassifier()
model.fit(arreglo[:-1],  valores[3:])

In [ ]:
model.predict([arreglo[-1,:]])

array([0])

In [ ]:
arreglo = []
for i in range(0, valores.shape[0]-2):
  arreglo.append(valores[i:i+3])
  arreglo_numpy = np.array(arreglo)
  if i>3:
    print(arreglo_numpy)
    valores[:i]
    model = tree.DecisionTreeClassifier()
    model.fit(arreglo_numpy[:-1],  valores[:i])

[[4 7 1]
 [7 1 5]
 [1 5 0]
 [5 0 1]
 [0 1 4]]
[[4 7 1]
 [7 1 5]
 [1 5 0]
 [5 0 1]
 [0 1 4]
 [1 4 0]]
[[4 7 1]
 [7 1 5]
 [1 5 0]
 [5 0 1]
 [0 1 4]
 [1 4 0]
 [4 0 3]]
[[4 7 1]
 [7 1 5]
 [1 5 0]
 [5 0 1]
 [0 1 4]
 [1 4 0]
 [4 0 3]
 [0 3 8]]


In [ ]:
def suma(a, b):
  return a + b

In [ ]:
print(exec("suma(3,5)"))

None


In [ ]:
print(eval("suma(3,5)"))

8


In [ ]:
exec("a = 5; b = 6; variable = suma(a,b)")
variable

11

In [ ]:
for i in range(1000):

In [ ]:
X = np.ones([20,3])
y = np.random.randint(low=0, high=2, size=[20,1])

In [ ]:
print(X)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]]


In [ ]:
from sklearn import model_selection

In [ ]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, stratify=y)

# TimeSeriesSplit

In [ ]:
import numpy as np
from sklearn.model_selection import TimeSeriesSplit

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4], [4,5], [7,3]])
print(X)
y = np.array([1, 2, 3, 4, 5, 6, 7, 8])
tscv = TimeSeriesSplit(n_splits=3)
print(tscv)
for train_index, test_index in tscv.split(X):
  print("TRAIN:", train_index, "TEST:", test_index)
  X_train, X_test = X[train_index], X[test_index]
  y_train, y_test = y[train_index], y[test_index]

[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [4 5]
 [7 3]]
TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None)
TRAIN: [0 1] TEST: [2 3]
TRAIN: [0 1 2 3] TEST: [4 5]
TRAIN: [0 1 2 3 4 5] TEST: [6 7]


# Entrenamiento validacion y prueba en series de tiempo

In [ ]:
import numpy as np

In [ ]:
datos = np.random.randint(low=0, high=10, size=20)
datos

array([6, 0, 6, 1, 1, 4, 6, 4, 2, 2, 2, 4, 2, 9, 1, 4, 4, 6, 5, 5])

In [ ]:
lista = list(range(20))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
from sklearn.model_selection import train_test_split

Cuando rompo en entrenamiento y prueba en series de tiempo debo garantizar que se mantenga la temporalidad. De tal forma que los datos más antiguos queden asociados al entrenamiento y los datos más nuevos al conjunto de prueba. En sklearn podemos usar `train_test_split` con el parametro `shuffle`.

In [ ]:
X_train, X_test, lista_train, lista_test = train_test_split(datos, lista, test_size=0.3, shuffle=False)

In [ ]:
lista_train, lista_test

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], [14, 15, 16, 17, 18, 19])

In [ ]:
X_train, X_test, lista_train, lista_test = train_test_split(datos, lista, test_size=0.1, shuffle=False)

In [ ]:
lista_train, lista_test

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], [18, 19])

In [ ]:
from sklearn.model_selection import TimeSeriesSplit

In [ ]:
tsp = TimeSeriesSplit(n_splits=2, )

In [ ]:
list(tsp.split(X_train))

[(array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
  array([12, 13, 14, 15, 16, 17]))]

# Validación cruzada de retencion ( hold-out cross validation)

In [ ]:
X_train_holdout, X_val_holdout, lista_train_holdout, lista_val_holdout = train_test_split(X_train, lista_train, test_size=0.3, shuffle=False)

In [ ]:
lista_train_holdout, lista_val_holdout

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17])

# Time Series Split

In [ ]:
from sklearn.model_selection import TimeSeriesSplit

In [ ]:
tsp = TimeSeriesSplit(n_splits=6, )

In [ ]:
lista = list(range(20))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
lista_train

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [ ]:
for train_index, test_index in tsp.split(lista_train):
  print("entrenamiento:", train_index, "prueba:", test_index)

entrenamiento: [0 1 2 3 4 5] prueba: [6 7]
entrenamiento: [0 1 2 3 4 5 6 7] prueba: [8 9]
entrenamiento: [0 1 2 3 4 5 6 7 8 9] prueba: [10 11]
entrenamiento: [ 0  1  2  3  4  5  6  7  8  9 10 11] prueba: [12 13]
entrenamiento: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13] prueba: [14 15]
entrenamiento: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] prueba: [16 17]


# Ejercicio 1.1

In [ ]:
def funcion(p, seed):
  # Cargar datos a partir de datasets.
  # train_test_split(x,y, test_size, random_state, stratify)

In [ ]:
np.random.seed(3)

# Lista a matriz

In [ ]:
lista = [3, 5, 6, 8]

In [ ]:
arreglo = np.array(lista)
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arreglo.shape

(20,)

In [ ]:
lista2 = [lista]
lista2

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]

In [ ]:
np.array(lista2)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [ ]:
np.array(lista2).shape

(1, 20)

# Redes neuronales

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X, y = make_classification(n_samples=100, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
                                                     random_state=1)

X.shape
y

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0])

Por defecto, Sklearn usa 1 sola capa oculta y 100 neuronas.

[Redes Neuronales](http://playground.tensorflow.org/#activation=relu&regularization=L2&batchSize=10&dataset=spiral&regDataset=reg-plane&learningRate=0.03&regularizationRate=0.1&noise=0&networkShape=7,8,8&seed=0.33146&showTestData=false&discretize=false&percTrainData=50&x=true&y=true&xTimesY=false&xSquared=false&ySquared=false&cosX=false&sinX=false&cosY=false&sinY=false&collectStats=false&problem=classification&initZero=false&hideText=false)

In [ ]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)
clf.predict_proba(X_test[:1])
clf.predict(X_test[:5, :])
clf.score(X_test, y_test)

0.88

Cuando deseo más capas y más neuronas utilizo `hidden_layer_sizes`. Cada número representa el número de neuronas ocultas de la capa dada.

In [ ]:
clf = MLPClassifier(hidden_layer_sizes=(100, 100, 100, 100), random_state=1, max_iter=300).fit(X_train, y_train)
clf.predict_proba(X_test[:1])
clf.predict(X_test[:5, :])
clf.score(X_test, y_test)

0.88

In [ ]:
clf = MLPClassifier(hidden_layer_sizes=(100, 200, 100, 20, 20), random_state=1, max_iter=300).fit(X_train, y_train)
clf.predict_proba(X_test[:1])
clf.predict(X_test[:5, :])
clf.score(X_test, y_test)

0.92

# Potencias de 2 en un kernel gaussiano

A esto se le conoce como una escala logaritmica

In [ ]:
lista = np.arange(-20,20,1, dtype=np.float)
lista

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([-20., -19., -18., -17., -16., -15., -14., -13., -12., -11., -10.,
        -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,   1.,
         2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
        13.,  14.,  15.,  16.,  17.,  18.,  19.])

In [ ]:
[2**i for i in lista]

[9.5367431640625e-07,
 1.9073486328125e-06,
 3.814697265625e-06,
 7.62939453125e-06,
 1.52587890625e-05,
 3.0517578125e-05,
 6.103515625e-05,
 0.0001220703125,
 0.000244140625,
 0.00048828125,
 0.0009765625,
 0.001953125,
 0.00390625,
 0.0078125,
 0.015625,
 0.03125,
 0.0625,
 0.125,
 0.25,
 0.5,
 1.0,
 2.0,
 4.0,
 8.0,
 16.0,
 32.0,
 64.0,
 128.0,
 256.0,
 512.0,
 1024.0,
 2048.0,
 4096.0,
 8192.0,
 16384.0,
 32768.0,
 65536.0,
 131072.0,
 262144.0,
 524288.0]

# Partición

In [ ]:
arreglo = [4, 5, 6, 7, 2]
porcentaje = 0.3

In [ ]:
len(arreglo)

5

In [ ]:
5 * porcentaje

1.5

In [ ]:
arreglo[:2], arreglo[2:]

([4, 5], [6, 7, 2])

In [ ]:
print(round(2.5))

print(round(0.05, 1))

2
0.1


In [ ]:
import numpy as np

print(np.around(2.5))
print(np.around(0.05, 1))

2.0
0.0


# Machine learning

In [ ]:
import pandas as pd
from sklearn import ensemble
from sklearn import datasets

In [ ]:
X, y = datasets.load_iris(return_X_y= True)

In [ ]:
model = ensemble.RandomForestClassifier()
model.fit(X, y)

RandomForestClassifier()

In [ ]:
model.predict([[5.1, 3.5, 1.4, 0.2], [5.1, 3.5, 1.4, 0.2]])[0]

0

# Pandas sin indice

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(np.random.random_integers(0, 10, size=(5,5)))
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  """Entry point for launching an IPython kernel.


0   1  2   3  4
0  5  10  2   6  8
1  8   6  7  10  5
2  9   1  4   9  3
3  1   5  2   3  2
4  6   0  5   0  9

In [ ]:
print(df.iloc[0].values)
print(df.iloc[0].index)


[ 5 10  2  6  8]
RangeIndex(start=0, stop=5, step=1)


In [ ]:
df.loc[:, 2].values

array([2, 7, 4, 2, 5])

# Troceados python vs numpy vs dataframe

In [ ]:
arreglo = [3, 5, 6, 7]

In [ ]:
print(arreglo[1:3])
print(arreglo[:3])
print(arreglo[1:])
print(arreglo[1::3])

[5, 6]
[3, 5, 6]
[5, 6, 7]
[5]


In [ ]:
arreglo = [[3,5,6,6],[21,1,24,54]]
print(arreglo)

[[3, 5, 6, 6], [21, 1, 24, 54]]


In [ ]:
arreglo[0][0:2]

[3, 5]

In [ ]:
[arreglo[0][0]] + [arreglo[1][0]]

[3, 21]

In [ ]:
import numpy as np

In [ ]:
arreglo = np.array([[3,5,6,6],[21,1,24,54]])
print(arreglo)

[[ 3  5  6  6]
 [21  1 24 54]]


In [ ]:
arreglo[0, 0:2]

array([3, 5])

In [ ]:
arreglo[:, 0]

array([ 3, 21])

# Funciones dentro de funciones

In [ ]:
import numpy as np
#Función para generar la función de predicción de un
# clasificador entrenado previamente.
def gen_pred_fun(clf):
    def pred_fun(x1, x2):
        x = np.array([[x1, x2]])
        return clf.predict(x)
    return pred_fun

In [ ]:
class Model():
  def predict(self, x):
    return x

In [ ]:
clf_model = Model()
clf_model.predict(2)

2

In [ ]:
fun = gen_pred_fun(clf_model)

In [ ]:
fun(2, 3)

array([[2, 3]])