In [ ]:
import numpy as np
from sklearn import datasets

In [ ]:
X, y = datasets.load_iris()['data'], datasets.load_iris()['target']

In [ ]:
X, y = datasets.load_iris(return_X_y=True)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier()
knn.fit(X,y)



KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
def predict(clf, X_prima):
  return clf.predict(X_prima)

In [ ]:
y_predict = predict(knn, X)

In [ ]:
from sklearn import metrics

In [ ]:
metrics.f1_score(y, y_predict, average="micro")

0.9666666666666667

In [ ]:
# Función para visualizar un conjunto de datos de dos variables en un plano 2D
def plot_data(X, y, model = None, ax = None, title=None):

    if ax is None:
      _, ax = plt.subplots(dpi = 110)

    if model is not None: 
      pred_fun = gen_pred_fun(model)
      plot_decision_region(X, pred_fun, ax)

    y_unique = np.unique(y)    
    df = pd.DataFrame({'x1': X[:,0], 'x2': X[:,1], 'Clases': y})
    sns.set_theme()
    sns.scatterplot(data = df, x = 'x1', y = 'x2', 
                    hue = 'Clases',style = 'Clases', ax = ax, palette = 'Set1').set_title(title)

In [ ]:
from sklearn import datasets

X, y = datasets.make_moons(n_samples=10, noise=0, random_state=0)

In [ ]:
X

array([[ 6.12323400e-17,  1.00000000e+00],
       [ 1.70710678e+00, -2.07106781e-01],
       [-1.00000000e+00,  1.22464680e-16],
       [ 2.00000000e+00,  5.00000000e-01],
       [ 7.07106781e-01,  7.07106781e-01],
       [ 2.92893219e-01, -2.07106781e-01],
       [ 1.00000000e+00, -5.00000000e-01],
       [-7.07106781e-01,  7.07106781e-01],
       [ 1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  5.00000000e-01]])

In [ ]:
plot_data(X, y)

In [ ]:
arreglo = np.random.randint(low=0,high=3, size=[40])
arreglo

array([0, 2, 0, 2, 1, 2, 2, 0, 0, 0, 1, 2, 0, 1, 0, 1, 1, 2, 0, 1, 1, 1,
       1, 0, 2, 1, 2, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 2])

In [ ]:
arreglo==0

array([ True, False,  True, False, False, False, False,  True,  True,
        True, False, False,  True, False,  True, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False,  True,  True, False, False,  True, False, False, False,
        True, False, False, False])

In [ ]:
arreglo[(arreglo==0) | (arreglo==1)]

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1])

In [ ]:
p = p, random_state = random_state